### ISSUE TITLE
How to do parallel execution?

### ISSUE THREAD

**Issue by Evgeniya-Smoliak** [reportportal/agent-java-karate#3]
Please, could you inform me how to do parallel execution with KarateReportPortalRunner, so, in karate documentation, it is written not to use the @RunWith when you want to run tests in parallel via  CucumberRunner.parallel() ?

**Comment by filland** [comment]
@rahul267 could you help ?

**Comment by rahul267** [comment]
Yes , this feature completely uses junit  runner to implement the Karate + report portal configuration .
We can have this as new feature in this plugin to support parallel runs .

**Comment by Evgeniya-Smoliak** [comment]
@rahul267 could you add an example to agent-java-karate to show how to support parallel runs?

**Comment by RG108** [comment]
@rahul267 

I tried running the maven project which is pointed to master but while running the sample project I am getting the below issue:

Feature: Quote generator
12:01:10.676 ERROR c.e.r.s.ReportPortal - main - Cannot build ReportPortal client
java.net.MalformedURLException: no protocol: yourinstancepleaseedit
	at java.base/java.net.URL.<init>(URL.java:627)
	at java.base/java.net.URL.<init>(URL.java:523)
	at java.base/java.net.URL.<init>(URL.java:470)
	at com.epam.reportportal.service.ReportPortal$Builder.defaultClient(ReportPortal.java:274)
	at com.epam.reportportal.service.ReportPortal$Builder.build(ReportPortal.java:233)
	at com.epam.reportportal.cucumber.AbstractReporter.buildReportPortal(AbstractReporter.java:101)
	at com.epam.reportportal.cucumber.AbstractReporter$1.get(AbstractReporter.java:71)
	at com.epam.reportportal.cucumber.AbstractReporter$1.get(AbstractReporter.java:64)
	at rp.com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:120)
	at com.epam.reportportal.cucumber.ScenarioReporter$1.get(ScenarioReporter.java:60)
	at com.epam.reportportal.cucumber.ScenarioReporter$1.get(ScenarioReporter.java:53)
	at rp.com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:120)
	at com.epam.reportportal.cucumber.ScenarioReporter.getRootItemId(ScenarioReporter.java:107)
	at com.epam.reportportal.cucumber.AbstractReporter.beforeScenario(AbstractReporter.java:149)
	at com.epam.reportportal.cucumber.AbstractReporter.startOfScenarioLifeCycle(AbstractReporter.java:322)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at cucumber.runtime.Utils$1.call(Utils.java:40)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:34)
	at cucumber.runtime.RuntimeOptions$1.invoke(RuntimeOptions.java:294)
	at com.sun.proxy.$Proxy11.startOfScenarioLifeCycle(Unknown Source)
	at cucumber.runtime.junit.JUnitReporter.startOfScenarioLifeCycle(JUnitReporter.java:238)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:39)
	at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:102)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70)
	at KarateReportPortalRunner.runChild(KarateReportPortalRunner.java:125)
	at com.intuit.karate.junit4.Karate.runChild(Karate.java:37)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at com.intuit.karate.junit4.Karate.run(Karate.java:129)
	at KarateReportPortalRunner.run(KarateReportPortalRunner.java:130)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
Warning: Nashorn engine is planned to be removed from a future JDK release
12:01:12.257 WARN  c.i.karate - main - not a js function or feature file: read('classpath:karate-config.js') - [type: NULL, value: null]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by cucumber.deps.com.thoughtworks.xstream.core.util.Fields (file:/Users/cex/.m2/repository/info/cukes/cucumber-jvm-deps/1.0.5/cucumber-jvm-deps-1.0.5.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of cucumber.deps.com.thoughtworks.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

  Scenario: Fetch random quote                            [90m# feature/Test.feature:2[0m
    [36mGiven [0m[36murl [0m[36m[1m'http://jsonplaceholder.typicode.com/posts'[0m [90m# StepDefs.url(String)[0m
    [36mGiven [0m[36mpath '1'[0m
    [36mWhen [0m[36mmethod GET[0m
    [36mThen [0m[36mstatus 200[0m
12:01:12.760 ERROR c.e.r.s.ReportPortal - main - Cannot build ReportPortal client
java.net.MalformedURLException: no protocol: yourinstancepleaseedit
	at java.base/java.net.URL.<init>(URL.java:627)
	at java.base/java.net.URL.<init>(URL.java:523)
	at java.base/java.net.URL.<init>(URL.java:470)
	at com.epam.reportportal.service.ReportPortal$Builder.defaultClient(ReportPortal.java:274)
	at com.epam.reportportal.service.ReportPortal$Builder.build(ReportPortal.java:233)
	at com.epam.reportportal.cucumber.AbstractReporter.buildReportPortal(AbstractReporter.java:101)
	at com.epam.reportportal.cucumber.AbstractReporter$1.get(AbstractReporter.java:71)
	at com.epam.reportportal.cucumber.AbstractReporter$1.get(AbstractReporter.java:64)
	at rp.com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:120)
	at com.epam.reportportal.cucumber.ScenarioReporter.afterLaunch(ScenarioReporter.java:116)
	at com.epam.reportportal.cucumber.AbstractReporter.close(AbstractReporter.java:365)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at cucumber.runtime.Utils$1.call(Utils.java:40)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:34)
	at cucumber.runtime.RuntimeOptions$1.invoke(RuntimeOptions.java:294)
	at com.sun.proxy.$Proxy11.close(Unknown Source)
	at cucumber.runtime.junit.JUnitReporter.close(JUnitReporter.java:232)
	at KarateReportPortalRunner.run(KarateReportPortalRunner.java:132)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
com.epam.reportportal.exception.InternalReportPortalClientException: Cannot build ReportPortal client
	at com.epam.reportportal.service.ReportPortal$Builder.build(ReportPortal.java:241)
	at com.epam.reportportal.cucumber.AbstractReporter.buildReportPortal(AbstractReporter.java:101)
	at com.epam.reportportal.cucumber.AbstractReporter$1.get(AbstractReporter.java:71)
	at com.epam.reportportal.cucumber.AbstractReporter$1.get(AbstractReporter.java:64)
	at rp.com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:120)
	at com.epam.reportportal.cucumber.ScenarioReporter.afterLaunch(ScenarioReporter.java:116)
	at com.epam.reportportal.cucumber.AbstractReporter.close(AbstractReporter.java:365)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at cucumber.runtime.Utils$1.call(Utils.java:40)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:34)
	at cucumber.runtime.RuntimeOptions$1.invoke(RuntimeOptions.java:294)
	at com.sun.proxy.$Proxy11.close(Unknown Source)
	at cucumber.runtime.junit.JUnitReporter.close(JUnitReporter.java:232)
	at KarateReportPortalRunner.run(KarateReportPortalRunner.java:132)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
Caused by: java.net.MalformedURLException: no protocol: yourinstancepleaseedit
	at java.base/java.net.URL.<init>(URL.java:627)
	at java.base/java.net.URL.<init>(URL.java:523)
	at java.base/java.net.URL.<init>(URL.java:470)
	at com.epam.reportportal.service.ReportPortal$Builder.defaultClient(ReportPortal.java:274)
	at com.epam.reportportal.service.ReportPortal$Builder.build(ReportPortal.java:233)
	... 23 more

Could you please suggest what might be the causing the issue, please ?

**Comment by tvamev** [comment]
Hi, is this addressed? Any updates please? With such a beautiful reportportal, this is a big issue. @rahul267  @filland
