### ISSUE TITLE
Unable to retrieve the table column value from MS SQL using agent-java-karate

### ISSUE THREAD

**Issue by RG108** [reportportal/agent-java-karate#6]
Hi,
I am getting below issue while retrieving the database value using agent-java-karate

12:02:51.937 DEBUG o.s.j.s.JdbcUtils - main - JDBC driver has limited support for JDBC 4.1 'getObject(int, Class)' method
java.sql.SQLException: Conversion not supported for type java.lang.Object
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
	at com.mysql.cj.jdbc.result.ResultSetImpl.getObject(ResultSetImpl.java:1475)
	at org.springframework.jdbc.support.JdbcUtils.getResultSetValue(JdbcUtils.java:212)
	at org.springframework.jdbc.core.SingleColumnRowMapper.getColumnValue(SingleColumnRowMapper.java:149)
	at org.springframework.jdbc.core.SingleColumnRowMapper.mapRow(SingleColumnRowMapper.java:114)
	at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:94)
	at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:61)
	at org.springframework.jdbc.core.JdbcTemplate$1QueryStatementCallback.doInStatement(JdbcTemplate.java:439)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:375)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:451)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:461)
	at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:472)
	at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:479)

I use spring framework to get the MSSQL or SQL values and it worked fine with latest karate version 0.9.2 but it is breaking using the agent. 

Please suggest further. I am deeply stuck due to this.
@lexecon , @rahul267 , @avarabyeu

**Comment by HardNorth** [comment]
@RG108 I don't believe that it's something related to ReportPortal and Karate integration for ReportPortal. Please address this question to corresponding community, E.G. Spring-JDBC.
